export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
export const SET_MODAL_DATA = 'SET_MODAL_DATA'

export const FETCH_USERS = 'FETCH_USERS'

export const FETCH_EVENTS = 'FETCH_EVENTS'
export const CREATE_EVENT = 'CREATE_EVENT'
export const EDIT_EVENT = 'EDIT_EVENT'
export const REMOVE_EVENT = 'REMOVE_EVENT'
export const TRY_REMOVE_EVENT = 'TRY_REMOVE_EVENT'
export const STORE_CLEAR_EVENTS = 'STORE_CLEAR_EVENTS'

export const FETCH_ROOMS = 'FETCH_ROOMS'

// Event types
export const EMPTY_EVENT = 'EMPTY_EVENT'
export const REAL_EVENT = 'REAL_EVENT'

export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT'

export const SET_CURRENT_DATE = 'SET_CURRENT_DATE'
export const SET_NEXT_DATE = 'SET_NEXT_DATE'
export const SET_PREVIOUS_DATE = 'SET_PREVIOUS_DATE'

export const SET_APP_STATUS = 'SET_APP_STATUS'
export const APP_STATUS_LOADING = 'LOADING'
export const APP_STATUS_LOADED = 'LOADED'
export const APP_STATUS_FETCHING_FAILED = 'FETCHING_FAILED'

export const HANDLE_EVENT_TOOLTIP = 'HANDLE_EVENT_TOOLTIP'

export const SET_BOOKING_ROOM_TYPE = 'SET_BOOKING_ROOM_TYPE'
export const BOOKING_ROOM_TYPE_EDITING = 'editing'
export const BOOKING_ROOM_TYPE_CREATING = 'creating'

export const RESET_CURRENT_EVENT = 'RESET_CURRENT_EVENT'